INSERT INTO STATUS_PEDIDO (ID, STATUS) VALUES (1, 'Aberto');
INSERT INTO STATUS_PEDIDO (ID, STATUS) VALUES (2, 'Preparando');
INSERT INTO STATUS_PEDIDO (ID, STATUS) VALUES (3, 'Entrega');
INSERT INTO STATUS_PEDIDO (ID, STATUS) VALUES (4, 'Finalizado');